# Generated by Django 5.0.6 on 2024-06-15 20:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Question id')),
                ('description', models.TextField(verbose_name='Question description')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Answer id')),
                ('description', models.TextField(verbose_name='Answer description')),
                ('is_valid', models.BooleanField(verbose_name='Answer validity')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.question', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Quiz id')),
                ('title', models.CharField(max_length=200, verbose_name='Quiz title')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Quiz content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Quiz created at')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Quiz updated at')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='classroom.classroom', verbose_name='Classroom')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.quiz', verbose_name='Quiz'),
        ),
        migrations.CreateModel(
            name='StudentQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Mark')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='Answered at')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='quiz.quiz', verbose_name='Quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_quizzes', to='account.studentprofile', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Student quiz relation',
                'verbose_name_plural': 'Student quiz relations',
                'ordering': ('-mark', '-answered_at'),
            },
        ),
    ]
