# Generated by Django 5.0.6 on 2024-06-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='studentquiz',
            constraint=models.UniqueConstraint(fields=('student', 'quiz'), name='student-quiz'),
        ),
    ]
