# Generated by Django 5.0.6 on 2024-07-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_studentanswer_studentanswer_student_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentquiz',
            name='mark',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Mark'),
        ),
    ]
