# Generated by Django 5.0.6 on 2024-06-15 20:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Classroom id')),
                ('name', models.CharField(max_length=200, verbose_name='Classroom name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Classroom created at')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='account.teacherprofile', verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Classroom',
                'verbose_name_plural': 'Classrooms',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='StudentClassroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date joined')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.classroom', verbose_name='Classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.studentprofile', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Student Classroom relation',
                'verbose_name_plural': 'Student Classroom relations',
                'ordering': ('-date_joined',),
            },
        ),
        migrations.AddConstraint(
            model_name='studentclassroom',
            constraint=models.UniqueConstraint(fields=('student', 'classroom'), name='student-classroom'),
        ),
    ]
