# Generated by Django 5.0.6 on 2024-06-14 11:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Question id')),
                ('description', models.TextField(verbose_name='Question description')),
            ],
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'ordering': ('date_of_birth',), 'verbose_name': 'Student Profile', 'verbose_name_plural': 'Student Profiles'},
        ),
        migrations.AlterModelOptions(
            name='teacherprofile',
            options={'ordering': ('-years_of_experience', 'date_of_birth'), 'verbose_name': 'Teacher Profile', 'verbose_name_plural': 'Teacher Profiles'},
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Student id'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Teacher id'),
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Classroom id')),
                ('name', models.CharField(max_length=200, verbose_name='Classroom name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Classroom created at')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='classroom.teacherprofile', verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Classroom',
                'verbose_name_plural': 'Classrooms',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CoursePost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Course id')),
                ('title', models.CharField(max_length=200, verbose_name='Course title')),
                ('content', models.TextField(verbose_name='Course content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Course created at')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Course updated at')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='classroom.classroom', verbose_name='Classroom')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Comment id')),
                ('content', models.TextField(verbose_name='Comment content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Comment created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Comment updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='classroom.coursepost', verbose_name='Course post')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Answer id')),
                ('description', models.TextField(verbose_name='Answer description')),
                ('is_valid', models.BooleanField(verbose_name='Answer validity')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='classroom.question', verbose_name='Question')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Quiz id')),
                ('title', models.CharField(max_length=200, verbose_name='Quiz title')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Quiz content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Quiz created at')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Quiz updated at')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='classroom.classroom', verbose_name='Classroom')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='classroom.quiz', verbose_name='Quiz'),
        ),
        migrations.CreateModel(
            name='StudentClassroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date joined')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.teacherprofile', verbose_name='Classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.studentprofile', verbose_name='Student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Mark')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='classroom.quiz', verbose_name='Quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_quizzes', to='classroom.studentprofile', verbose_name='Student')),
            ],
        ),
    ]
